version: '3.4'
services:
  api:
    image: weather-api
    container_name: 'weather-api'
    build:
      context: api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - SERVE_ON_PORT=$API_DOCKER_PORT
    networks:
      - weather
  
  web:
    image: weather-web
    container_name: 'weather-web'
    build:
      context: web
      args:
        - CLIENT_API_BASE_URL=$WEB_API_BASE_URL
      dockerfile: ./Dockerfile
    env_file: ./.env
    networks:
      - weather
  
  nginx:
    depends_on:
      - api
      - web
    image: weather-nginx
    container_name: 'weather-nginx'
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - weather 

networks:
  weather: