version: '3.4'
services:
  api:
    image: weather-api
    container_name: 'weather-api'
    build:
      context: api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - ACCU_WEATHER_BASE_URL=$ACCU_WEATHER_BASE_URL
      - ACCU_WEATHER_KEY=$ACCU_WEATHER_KEY
    networks:
      - weather
  
  web:
    image: weather-web
    container_name: 'weather-web'
    build:
      context: web
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_GOOGLE_MAP_KEY=$GOOGLE_MAP_KEY
        - REACT_APP_API_BASE_URL=$API_BASE_URL
    networks:
      - weather
  
  nginx:
    depends_on:
      - api
      - web
    image: weather-nginx
    container_name: 'weather-nginx'
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - $NGINX_LOCAL_PORT:$NGINX_DOCKER_PORT
    networks:
      - weather 

networks:
  weather: